// Framework-free domain types shared by the engine, the data layer and the worker.

export type Period = 'year' | 'quarter' | 'month' | 'week' | 'day' | 'hour' | 'minute' | 'second';
export type Confidence = 'official' | 'estimate' | 'modelled';
export type Provenance = 'reported' | 'interpolated' | 'carried' | 'allocated';
export type MetricKind = 'flow' | 'stock';
export type Scale = 'linear' | 'sqrt' | 'log';

export const CATEGORY_IDS = [
  'consumer',
  'demography-health',
  'environment-energy',
  'digital',
  'economy',
  'geography',
  'user',
] as const;
export type CategoryId = (typeof CATEGORY_IDS)[number];

export const UNIT_IDS = [
  'count',
  'tonne',
  'kg',
  'litre',
  'kWh',
  'TWh',
  'byte',
  'usd',
  'hour',
  'barrel',
  'hectare',
  'km2',
  'teu',
  'm3',
] as const;
export type UnitId = (typeof UNIT_IDS)[number];

export const NAMED_PROFILES = ['uniform', 'localDaytime', 'waking'] as const;
export type NamedProfile = (typeof NAMED_PROFILES)[number];
export type TemporalProfile = NamedProfile | { hourly: number[] };

export interface I18nText {
  en: string;
  it: string;
}

export interface SeriesPoint {
  /** 'world' or an ISO 3166-1 alpha-3 code (or a World Pulse pseudo-code such as XKX). */
  scope: string;
  year: number;
  value: number;
  /** Required for flows: the value is "per period". Ignored for stocks. */
  period?: Period;
  sourceId: string;
  confidence: Confidence;
  note?: string;
}

export interface Source {
  title: string;
  publisher: string;
  url: string;
  published?: string;
  accessed: string;
}

export interface MetricFile {
  schemaVersion: 1;
  id: string;
  category: CategoryId;
  name: I18nText;
  description: I18nText;
  unit: UnitId;
  unitLabel: I18nText;
  kind: MetricKind;
  temporalProfile?: TemporalProfile;
  allocation?: { proxy: string; exclude?: string[] };
  resolution?: { maxYearGap?: number };
  visual?: { color?: string; icon?: string; scale?: Scale };
  /** Shown in the live ticker. */
  featured?: boolean;
  /** Individual points (hand-curated data). */
  series?: SeriesPoint[];
  /** Compact tabular points (generated by the ETL): one row per scope aligned with `years`. */
  tables?: SeriesTable[];
  sources: Record<string, Source>;
}

/** Compact series block: same source/confidence/period for every value. `null` = no value for that year. */
export interface SeriesTable {
  sourceId: string;
  confidence: Confidence;
  /** Required for flows (value is "per period"). */
  period?: Period;
  note?: string;
  years: number[];
  /** Scope ('world' or ISO3) → values aligned with `years`. */
  values: Record<string, (number | null)[]>;
}

export interface Manifest {
  schemaVersion: 1;
  defaultMetric: string;
  metrics: string[];
  proxies: string[];
}

/** Resolved value for one scope at one target year. `value` is per second for flows, a level for stocks. */
export interface ResolvedValue {
  value: number;
  dataYear: number;
  provenance: Provenance;
  confidence: Confidence;
  sourceId: string | null;
  note?: string;
}

export interface CountryValue extends ResolvedValue {
  iso3: string;
}

export interface WorldValue {
  value: number;
  /** 'sum' when there is no world series and the world value is the sum of known countries. */
  provenance: Provenance | 'sum';
  dataYear: number | null;
  confidence: Confidence;
  sourceId: string | null;
}

export interface MetricSnapshot {
  metricId: string;
  year: number;
  kind: MetricKind;
  unit: UnitId;
  world: WorldValue;
  countries: CountryValue[];
  /** Part of the world value that could not be placed on any country (no allocation proxy declared). */
  unallocated: number;
  /** Share (0–100) of the world value backed by country-level data (not allocated, not unallocated). */
  coveragePct: number;
  coverageBasis: 'world' | 'proxy';
  warnings: string[];
}

export interface YearRange {
  min: number;
  max: number;
}
